
dataset_attributes:
  depth_images_dir: /datastore/npl/ViInfographicCaps/data/depth_images_npy
  image_features:
    # train: /datastore/npl/ViInfographicCaps/data/swintextspotter, /datastore/npl/ViInfographicCaps/data/faster_rcnn
    train: /datastore/npl/ViInfographicCaps/data/swintextspotter, /datastore/npl/ViInfographicCaps/data/faster_rcnn
    val: /datastore/npl/ViInfographicCaps/data/swintextspotter, /datastore/npl/ViInfographicCaps/data/faster_rcnn
    test: /datastore/npl/ViInfographicCaps/data/swintextspotter, /datastore/npl/ViInfographicCaps/data/faster_rcnn
    # - open_images/detectron_fix_100/fc6/test,m4c_textvqa_ocr_en_frcn_features/test_images
  imdb_files:
    # train: /data/npl/ViInfographicCaps/data/train_imdb.npy
    train: /datastore/npl/ViInfographicCaps/workspace/baseline/DEVICE/DEVICE-Image-Captioning/data/train_imdb.npy
    val: /datastore/npl/ViInfographicCaps/workspace/baseline/DEVICE/DEVICE-Image-Captioning/data/val_imdb.npy
    test: /datastore/npl/ViInfographicCaps/workspace/baseline/DEVICE/DEVICE-Image-Captioning/data/test_imdb.npy
model_attributes:
  image_dir: /datastore/npl/ViInfographicCaps/data/images
  model_clip: /datastore/npl/ViInfographicCaps/model/clip-vit-large-patch14
  fasttext_bin: ./utils/fasttext/wiki.vi.bin
  depth_images_dir: /datastore/npl/ViInfographicCaps/data/depth_images
  # fasttext_bin: utils/fasttext/wiki.vi.bin
  model_decoder: /datastore/npl/ViInfographicCaps/model/phobert-base
  hidden_size: 768
  ocr:
    dim: 256
    num_ocr: 100
  obj:
    dim: 1024
    num_obj: 100
  feature_dim: 2048 # d
  defum:
    num_layers: 100 # Num obj features
    activation: relu
    nhead: 1
  sgam:
    savo:
      top_k: 15
      vocab_path_en: /datastore/npl/ViInfographicCaps/workspace/baseline/DEVICE/DEVICE-Image-Captioning/data/object_vocab_en.txt
      vocab_path_vi: /datastore/npl/ViInfographicCaps/workspace/baseline/DEVICE/DEVICE-Image-Captioning/data/object_vocab_vi.txt
  mutimodal_transformer:
    num_layers: 4
    nhead: 12
    max_length: 32
    dropout: 0.1
  text_embedding:
    common_vocab: /datastore/npl/ViInfographicCaps/workspace/baseline/DEVICE/DEVICE-Image-Captioning/data/vocab.txt
    max_length: 30
    return_tensors: pt
  adjust_optimizer:
    lr_scale: 0.1 # scale lr for finetuning modules
optimizer_attributes:
  lr_scale: 0.1 # scale lr for finetuning modules
  params:
    eps: 1.0e-08
    lr: 1.0e-4
    weight_decay: 0.01
  type: AdamW
training_parameters:
  epochs: 26
  batch_size: 64
  early_stopping:
    patience: 5
  lr_scheduler:
    status: true
    type: "step"
    gamma : 0.1
    lr_steps:
      - 7000
    lr_ratio: 0.1
  max_iterations: 9000
  snapshot_interval: 1000
  metric_minimize: false
  seed: 2021


    