
dataset_attributes:
  image_features:
    # train: /data/npl/ViInfographicCaps/features/swintextspotter, /data/npl/ViInfographicCaps/features/faster_rcnn/features
    train: /data/npl/ViInfographicCaps/features/swintextspotter, /data/npl/ViInfographicCaps/features/faster_rcnn/features
    val: /data/npl/ViInfographicCaps/features/swintextspotter, /data/npl/ViInfographicCaps/features/faster_rcnn/features
    test: /data/npl/ViInfographicCaps/features/swintextspotter, /data/npl/ViInfographicCaps/features/faster_rcnn/features
    # - open_images/detectron_fix_100/fc6/test,m4c_textvqa_ocr_en_frcn_features/test_images
  imdb_files:
    # train: /data/npl/ViInfographicCaps/data/train_imdb.npy
    train: /data/npl/ViInfographicCaps/data/val_imdb.npy
    val: /data/npl/ViInfographicCaps/data/val_imdb.npy
    test: /data/npl/ViInfographicCaps/data/test_imdb.npy
model_attributes:
  image_dir: /data/npl/ViInfographicCaps/images/images
  model_clip: /data/npl/ViInfographicCaps/hf_model/clip-vit-large-patch14
  fasttext_bin: ./utils/fasttext/wiki.vi.bin
  depth_images_dir: /data/npl/ViInfographicCaps/features/depth_images
  # fasttext_bin: utils/fasttext/wiki.vi.bin
  model_decoder: /data/npl/ViInfographicCaps/hf_model/phobert-base
  hidden_size: 768
  ocr:
    dim: 256
    num_ocr: 100
  obj:
    dim: 1024
    num_obj: 100
  feature_dim: 2048 # d
  defum:
    num_layers: 100 # Num obj features
    activation: relu
    nhead: 1
  sgam:
    savo:
      top_k: 15
      vocab_path_en: /data/npl/ViInfographicCaps/workspace/baseline/DEVICE/DEVICE-Image-Captioning/data/object_vocab_en.txt
      vocab_path_vi: /data/npl/ViInfographicCaps/workspace/baseline/DEVICE/DEVICE-Image-Captioning/data/object_vocab_vi.text
  mutimodal_transformer:
    num_layers: 4
    nhead: 12
    max_length: 32
    dropout: 0.1
  text_embedding:
    common_vocab: ./data/vocab.txt
    max_length: 30
    return_tensors: pt
  adjust_optimizer:
    lr_scale: 0.1 # scale lr for finetuning modules
optimizer_attributes:
  lr_scale: 0.1 # scale lr for finetuning modules
  params:
    eps: 1.0e-08
    lr: 1.0e-4
    weight_decay: 0
  type: Adam
training_parameters:
  epochs: 2
  batch_size: 4
  iterations: 9000
  lr_scheduler:
    status: true
    type: "step"
    step_size: 7000
    gamma : 0.1
  lr_steps:
    - 6000
    - 10000
  lr_ratio: 0.1
  use_warmup: true
  warmup_factor: 0.2
  warmup_iterations: 1000
  max_iterations: 12000
  snapshot_interval: 500
  monitored_metric: m4c_textcaps/textcaps_bleu4
  metric_minimize: false
  seed: 2021


    